source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'sass-rails', '~> 5.0'
gem 'haml', '~> 4.0.1'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'devise', '~> 3.4.1'
gem 'mysql2', '~> 0.3.1'
gem 'jquery-rails', '~> 4.0.1'
gem 'angularjs-rails', '~> 1.3.1'
gem 'angular_rails_csrf', '~> 1.0.1'
gem 'omniauth-facebook', '~> 2.0.1'
gem 'cancancan', '~> 1.10'
gem 'angular-ui-bootstrap-rails', '~> 0.12.0'
gem 'jquery-ui-rails', '~> 5.0.1'
gem 'paperclip', '~> 4.2.1'
gem 'uglifier', '~> 2.7.1'
gem 'rails_12factor', '~> 0.0.1'


