default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: flow_dev
  username: root
  password: mysql

test:
  <<: *default
  database: flow_test
  username: root
  password: mysql

production:
  <<: *default
  adapter: postgresql
  database: flow
  username: flow
  password: <%= ENV['FLOW_DATABASE_PASSWORD'] %>
