default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: flow_development

test:
  <<: *default
  database: flow_test

production:
  <<: *default
  database: flow
  username: flow
  password: <%= ENV['FLOW_DATABASE_PASSWORD'] %>
